/*
 * cmd_system.c -- serial command handlers: *IDN?, BOOT, QSPI:ID?.
 * Split out of the old single commands.c (2026-09-29); the handlers are
 * unchanged. See commands.h for the file map.
 */
#include "commands.h"
#include "cmd_common.h"
#include "ctrlr_config.h"
#include "boot_jump.h"
#include "qspi_test.h"
#include "git_version.h"
#include "mcu.h"
#include "state_machine.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --------------------------------------------------------------------------
 * Identification / system
 * -------------------------------------------------------------------------- */

void cmd_idn(uart_instance_t *inst, char *args)
{
    char buf[96];
    (void)args;

    /* Board + firmware identity in one line, matching the sibling
       PFM-STM32G474 project's *IDN convention (OK <value>, space-
       separated fields) -- see ctrlr_config.h for the constants.

       4th field, FW_GIT_COMMIT (added 2026-09-29, ported from
       WHAM-XREX-PFMG474): exactly which git commit THIS firmware was
       built from, so a host can always tell what is really running on a
       board. A `-dirty` suffix flags a build made with uncommitted
       changes. Generated by python/gen_git_version.py (run by
       python/wham_build.py) into build/generated/git_version.h. */
    snprintf(buf, sizeof(buf), "OK %s %s %s %s%s\r\n",
             HW_BOARD_NAME, HW_BOARD_REV, FW_VERSION_STRING,
             FW_GIT_COMMIT, (FW_GIT_DIRTY != 0U) ? "-dirty" : "");
    uart_send(inst, buf);
}

#if (BOOT_JUMP_FEATURE_ENABLED != 0)
void cmd_boot(uart_instance_t *inst, char *args)
{
    (void)args;

    /* Refused while ARMED or FIRING (ERR 13): resetting into the ROM
       bootloader under load would drop the outputs uncontrolled. Allowed in
       IDLE and FAULT (a faulted board may need new firmware). */
    if ((SM_GetState() == SM_STATE_ARMED) || (SM_GetState() == SM_STATE_FIRING))
    {
        SendErr(inst, ERR_INVALID_STATE, "BOOT refused while ARMED or FIRING -- DISARM first");
        return;
    }

    /* uart_send() is blocking (HAL_UART_Transmit with HAL_MAX_DELAY), so
       this ACK is guaranteed to be fully on the wire before
       BootJump_RequestBootloader() resets the MCU below -- the operator
       (or a flashing script) sees "OK ENTERING BOOTLOADER" before the
       link drops. */
    uart_send(inst, "OK ENTERING BOOTLOADER\r\n");

    BootJump_RequestBootloader();
    /* Never returns. */
}
#endif /* BOOT_JUMP_FEATURE_ENABLED */

#if (QSPI_TEST_FEATURE_ENABLED != 0)
/* --------------------------------------------------------------------------
 * QSPI:ID?
 *
 * QUADSPI connectivity test against the W25Q128JVS wired to
 * PE12-PE15/PB10-PB11 (docs/pin_mapping_v4.csv) -- issues the flash's
 * standard JEDEC Read ID instruction (0x9F, plain 1-line mode, no Quad
 * Enable required) via QspiTest_ReadId() (qspi_test.h) and reports the
 * 3 raw bytes (Manufacturer, Memory Type, Capacity) as space-separated
 * uppercase hex, e.g. "OK EF 40 18" for a healthy Winbond part --
 * compare against the W25Q128JVS datasheet's own JEDEC ID table rather
 * than trusting any specific expected value hardcoded here (none is;
 * this command reports what the chip actually says, nothing assumed).
 * ERR 7 on any HAL_QSPI command/receive failure or timeout (e.g. no
 * chip present, a wiring fault, or the bus wedged) -- see
 * QspiTest_ReadId()'s own doc comment for exactly what that call does
 * and does not verify.
 * -------------------------------------------------------------------------- */
void cmd_qspi_id(uart_instance_t *inst, char *args)
{
    uint8_t id[3];
    char buf[32];
    (void)args;

    if (QspiTest_ReadId(id) == 0U)
    {
        SendErr(inst, ERR_QSPI_FAILED, "QUADSPI command failed or timed out");
        return;
    }

    snprintf(buf, sizeof(buf), "OK %02X %02X %02X\r\n",
             (unsigned int)id[0], (unsigned int)id[1], (unsigned int)id[2]);
    uart_send(inst, buf);
}
#endif /* QSPI_TEST_FEATURE_ENABLED */

/* --------------------------------------------------------------------------
 * DIAGnostic:OPTBytes? / DIAGnostic:RSTCause? / DIAGnostic:RSTCause:CLEar
 *
 * Boot diagnostics, ported from WHAM-XREX-PFMG474 (added 2026-09-29).
 * OPTBytes? reports the LIVE FLASH_OPTR register and the three bits that
 * decide the boot source (nBOOT0, nSWBOOT0, nBOOT1). RSTCause? reports the
 * RCC->CSR reset-cause flags (BOR brown-out/power-on, PIN NRST, SFT
 * software, IWDG/WWDG watchdog, LPWR low-power, OBL option-byte reload).
 * The boot banner (boot_diag.c) already captures and clears these each boot,
 * so RSTCause? mostly shows resets since then; CLEar zeroes the flags.
 * -------------------------------------------------------------------------- */
void cmd_diag_optbytes_query(uart_instance_t *inst, char *args)
{
    char buf[96];
    mcu_option_bytes_t ob;
    (void)args;

    Mcu_ReadOptionBytes(&ob);
    snprintf(buf, sizeof(buf), "OK OPTR=%08lX nBOOT0=%u nSWBOOT0=%u nBOOT1=%u\r\n",
             (unsigned long)ob.raw, (unsigned)ob.nBoot0, (unsigned)ob.nSwBoot0,
             (unsigned)ob.nBoot1);
    uart_send(inst, buf);
}

void cmd_diag_rstcause_query(uart_instance_t *inst, char *args)
{
    char buf[160];
    int  len = 0;
    mcu_reset_flags_t f;
    (void)args;

    Mcu_ReadResetFlags(&f);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, "OK CSR=%08lX", (unsigned long)f.raw);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " BOR=%u",   (unsigned)f.bor);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " PIN=%u",   (unsigned)f.pin);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " SFT=%u",   (unsigned)f.sft);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " IWDG=%u",  (unsigned)f.iwdg);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " WWDG=%u",  (unsigned)f.wwdg);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " LPWR=%u",  (unsigned)f.lpwr);
    len += snprintf(&buf[len], sizeof(buf) - (size_t)len, " OBL=%u",   (unsigned)f.obl);
    snprintf(&buf[len], sizeof(buf) - (size_t)len, "\r\n");
    uart_send(inst, buf);
}

void cmd_diag_rstcause_clear(uart_instance_t *inst, char *args)
{
    (void)args;
    Mcu_ClearResetFlags();   /* resets every flag above to 0 */
    uart_send(inst, "OK\r\n");
}
